trading/trading/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from journal.views import index, dashboard,\
    forex_detail, binary_detail, forex, binary, stamp
from user.views import RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('option/<str:option>', dashboard, name='dashboard'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('forex/new', forex, name='forex'),
    path('binary/new', binary, name='binary'),
    path('stamp/new', stamp, name='stamp'),
    path('stamp/delete/<uuid:id>', stamp, name='stamp_delete'),
    path('forex/<uuid:id>', forex_detail, name='forex_d'),
    path('binary/<uuid:id>', binary_detail, name='binary_d'),
    path('login', LoginView.as_view(template_name='login.html'), name='login'),
    path('register', RegisterView.as_view(), name='register'),
]

trading/journal/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.


class TimeStamp(models.Model):
    CHOICE = (('forex', 'forex'), ('binary', 'binary'))

    date = models.DateField()
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    option = models.CharField(choices=CHOICE, max_length=10, blank=True)

    def __str__(self):
        return f"Timestamp for {self.date}"

    class Meta:
        ordering = ['-date']


class BaseManager(models.Manager):
    arguments = ('r_text', 'l_text', 'r_image', 'l_image')

    def create_entry(self, **kwargs):
        r_text, l_text, r_image, l_image = [
            kwargs.pop(val) for val in self.arguments]

        entry = self.model.objects.create(**kwargs)
        Reason.objects.create(image=r_image, text=r_text, entry=entry)
        Lesson.objects.create(image=l_image, text=l_text, entry=entry)
        return entry


class BaseEntry(models.Model):
    entry_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    CHOICE = (('b', 'Buy'), ('s', 'Sell'))
    pair = models.CharField(max_length=7, )
    option = models.CharField(choices=CHOICE, max_length=1, default='b')
    objects = BaseManager()

    def __str__(self):
        return f"Entry for {self.pair} @ {self.stamp.date}"


class ForexEntry(BaseEntry):
    timeStart = models.DateTimeField()
    timeEnded = models.DateTimeField()
    rMultiple = models.IntegerField()
    SL = models.FloatField()
    price = models.FloatField()
    TP = models.FloatField()
    stamp = models.ForeignKey(
        TimeStamp, on_delete=models.CASCADE,
        related_name='forex'
    )


class BinaryEntry(BaseEntry):

    CHOICE = (
        ('w', 'Win'),
        ('l', 'Lose'),
    )
    payout = models.IntegerField()
    result = models.CharField(choices=CHOICE, max_length=1)
    time = models.TimeField()
    stamp = models.ForeignKey(
        TimeStamp, on_delete=models.CASCADE,
        related_name='binary'
    )


class ContentBase(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(
        upload_to='user_directory_path', blank=True, null=True)
    text = models.TextField()

    class Meta:
        abstract = True


class Reason(ContentBase):
    entry = models.OneToOneField(
        'BaseEntry',
        on_delete=models.CASCADE,
        related_name='reason'
    )


class Lesson(ContentBase):
    entry = models.OneToOneField(
        'BaseEntry',
        on_delete=models.CASCADE,
        related_name='lesson'
    )

trading/journal/forms.py
from django import forms
from .models import TimeStamp, ForexEntry, BinaryEntry, Reason, Lesson


class ReasonForm(forms.Form):
    r_text = forms.CharField(label='Reasons', widget=forms.Textarea)
    r_image = forms.FileField(label='Reason Image')


class LessonForm(forms.Form):
    l_text = forms.CharField(label='Lessons', widget=forms.Textarea)
    l_image = forms.FileField(label='Lesson Image')


class StampForm(forms.ModelForm):
    option = forms.CharField(
        widget=forms.HiddenInput,
    )

    owner = forms.CharField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = TimeStamp
        fields = '__all__'


class ForexEntryForm(forms.ModelForm):
    SL = forms.FloatField(label='Stop Loss', required=True)
    TP = forms.FloatField(label='Take Profit', required=True)
    timeStart = forms.DateTimeField(label='Trade Start')
    timeEnded = forms.DateTimeField(label='Trade End')
    stamp = forms.UUIDField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = ForexEntry
        fields = '__all__'


class BinaryEntryForm(forms.ModelForm):
    stamp = forms.UUIDField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = BinaryEntry
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pair'].widget.attrs.update(
            {
                'placeholder': 'Currency Traded'})
        self.fields['payout'].widget.attrs.update(
            {
                'placeholder': 'Payout Rate'})

trading/journal/views.py
# Django Imports
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.template import Context, engines
from django.template.backends.utils import csrf_token_lazy
from django.utils.dateparse import parse_date

# Dependency Imports
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response

# Application Imports
from .forms import ForexEntryForm, BinaryEntryForm, StampForm,\
    ReasonForm, LessonForm
from .models import ForexEntry, BinaryEntry, TimeStamp
from .serializers import StampSerializer, BinarySerializer, ForexSerializer


LINK_FOREX = "journal/fx.html"
LINK_BINARY = "journal/binary.html"
LINK_STAMP = "journal/stamp.html"

engine = engines['django'].engine
fx_template = engine.get_template(LINK_FOREX)
binary_template = engine.get_template(LINK_BINARY)
stamp_template = engine.get_template(LINK_STAMP)


def login(request):
    return render(request, 'login.html')


@login_required
def index(request):
    form = ForexEntryForm()
    return render(request, 'index.html', context={'form': form})


@login_required
def dashboard(request, option):
    if option == 'forex':
        form = ForexEntryForm()
    elif option == 'binary':
        form = BinaryEntryForm()
    else:
        return Http404()
    timestamps = TimeStamp.objects.filter(
        option=option,
        owner=request.user
    )
    context = {
        'form': form, 'option': option,
        't_form': StampForm(
            initial={'option': option, 'owner': request.user.id}),
        "stamps": timestamps,
        'l_form': LessonForm(),
        'r_form': ReasonForm()
    }
    return render(request, 'dashboard.html', context=context)


@api_view(['POST', 'DELETE'])
def stamp(request, id=None):
    if request.method == "POST":
        stamp = StampSerializer(data=request.data)

        if stamp.is_valid():
            stamp.save()
            csrf_token = csrf_token_lazy(request)
            date = parse_date(stamp.data["date"]).strftime('%B %d, %Y')
            context = Context(
                {"stamp": stamp.data, "csrf_token": csrf_token, 'date': date})
            data = dict(
                stamp.data,
                template=stamp_template.render(context=context))
            return Response(data=data)
        return Response(stamp.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        try:
            TimeStamp.objects.get(id=id).delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except TimeStamp.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)


def post_wrapper(request, serializer_class, template):
    if request.method == "POST":
        serializer = serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            csrf_token = csrf_token_lazy(request)
            context = Context(
                {"entry": serializer.data, "csrf_token": csrf_token})
            data = dict(
                serializer.data,
                template=template.render(context=context))
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def forex(request):
    return post_wrapper(request, ForexSerializer, fx_template)


@api_view(['POST'])
def binary(request):
    return post_wrapper(request, BinarySerializer, binary_template)


def detail_wrapper(request, entry, serializer_class, id):
    try:
        entry = entry.objects.get(entry_id=id)
    except ForexEntry.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'DELETE':
        entry.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    elif request.method == 'PUT':
        serializer = serializer_class(entry, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(data=serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE', 'PUT'])
def forex_detail(request, id):
    return detail_wrapper(request, ForexEntry, ForexSerializer, id)


@api_view(['DELETE', 'PUT'])
def binary_detail(request, id):
    return detail_wrapper(request, BinaryEntry, BinarySerializer, id)

trading/journal/templates/includes/binary_table.html
{% load static %}
<section class="option-heading">
<h2>Options Journal
</h2>
<a href="{% url 'dashboard' 'forex' %}" class="btn btn-dark float-right" type="">
  Move to Forex journal
</a>
</section>

<table class="table table-responsive-md table-dark">
  <thead>
    <tr>
      <th scope="col">Pair</th>
      <th scope="col">Time</th>
      <th scope="col">Option</th>
      <th scope="col">Reasons</th>
      <th scope="col">Win/Lose</th>
      <th scope="col">Lessons</th>
      <th scope="col">Payout Rate</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody id="table-body">
    {% for x in stamps %}
  	<tr data-stamp-id="{{ x.id }}">
  	<tr id="{{ x.id }}" data-stamp-id="{{ x.id }}">
  		<td colspan="8" class="text-center">
  		<h2>{{ x.date|date:"E d, Y" }}</h2>
  		<button id="modal" title="New Trade Entry" value="{{ x.id }}" class="btn btn-info">
		Create New Trade Entry <span><img class="ml-1" height="30" width="30" src="{% static 'img/add.svg' %}" alt=""></span></button>
		<form class="d-inline" id="delete_stamp_form" action="{% url 'stamp_delete' x.id %}" data-value="{{ x.id }}">
          {% csrf_token %}
          <button type="submit" id="stamp_delete" class="btn btn-danger">
          Delete TimeStamp <span><img class="ml-1" height="30" width="30" src="{% static 'img/delete.svg' %}" alt=""></span></button>
        </form>
    <p data-id="{{ x.id }}" class="m-0 mt-3">{% if x.binary.all %} {{ x.binary.all|length }} Entries {% else %} No Entries yet. {% endif %}</p>
	</td></tr>
  {% for entry in x.binary.all reversed%}
    <tr id="{{ entry.entry_id }}" data-stamp-id="{{ x.id }}">
      <td class="market">{{ entry.pair }}</td>
      <td>{{ entry.time|date:"G:i:s" }}</td>
      <td class="span">{% if entry.option == "b" %}<span class="badge badge-success">{{ entry.get_option_display }}</span>{% else %}<span class="badge badge-danger">{{ entry.get_option_display }}</span>{% endif %}</td>
      <td>
        <p>{{ entry.reason.text }}</p>
        <button class="btn btn-info" id="image" href="#">
          View Image
        </button>
      </td>
      <td class="span">{% if entry.result == "w" %}<span class="badge badge-success">{{ entry.get_result_display }}</span>{% else %}<span class="badge badge-danger">{{ entry.get_result_display }}</span>{% endif %}</td>
      <td>
        <p>{{ entry.lesson.text }}</p>
        <button class="btn btn-info" id="image" href="#">
          View Image
        </button>
      </td>
      <td>{{ entry.payout }}%</td>
      <td>
        <form id="delete_form" action="{% url 'binary_d' entry.entry_id %}" data-stamp="{{ x.id }}" data-value="{{ entry.entry_id }}">
          {% csrf_token %}
          <button type="submit" id="entry_delete" class="btn btn-danger">
          X</button>
        </form>
        </td>
    </tr>
    {% endfor %}
</tr>
{% empty %}
<tr class="text-center"> No Timestamps </tr>
    {% endfor %}
  </tbody>
</table>

trading/journal/templates/includes/forms.html
{% load crispy_forms_tags %}
{% load static %}
<div id="alertModal">
  <div class="modal-content container">
    <div class="row w-100 justify-content-center">
      <div id="alertBox" class="alert alert-danger text-center p-3 mt-5 col-sm-4" role="alert">
        <h5 class="mb-4"><strong>Are you sure ?</strong></h5>
        <button class="btn btn-danger" data-option="yes" type="">
        Yes
        </button>
        <button class="btn btn-success" data-option="no" type="">
        No
        </button>
      </div>
    </div>
  </div>
</div>

<div id="imageModal">
  <div class="modal-content container">
    <div class="row w-100 mt-5 pt-5 justify-content-center align-items-center">
      <div class="col-sm-12">
        <span class="float-right" id="imageClose"><strong>x</strong></span>
        <img class="w-100" src="{% static 'img/chart.png' %}">
      </div>
    </div>
  </div>
</div>


<div id="myModal">
  <style type="text/css">
    .asteriskField{
      display: none !important;
    }
  </style>
		<div class="modal-content container">
<div class="row w-100 justify-content-center">
  <div class="fx_wrapper" id="fx_wrap">
    <span id="span"><strong>x</strong></span>
  {% if option == 'binary' %}
      <form class="w-100" method="post" id="fx_form" action="{% url 'binary' %}" name="trading_form" novalidate>
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.pair|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.result|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.payout|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ l_form.l_text|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ r_form.r_text|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ l_form.l_image|as_crispy_field }}
      </div>

      <div class="form-group col-md-6">
        {{ r_form.r_image|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ form.option|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ form.time|as_crispy_field }}
      </div>
      {{ form.stamp }}
    </div>
    <button type="submit" class="btn btn-primary">Add Entry</button>
  </form>
  {% else %}
    <form class="w-100" id="fx_form" action="{% url 'forex' %}" method="post" name='trading_form' novalidate>

    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.pair|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.timeStart|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.timeEnded|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ l_form.l_text|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ r_form.r_text|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ l_form.l_image|as_crispy_field }}
      </div>

      <div class="form-group col-md-6">
        {{ r_form.r_image|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.price|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.TP|as_crispy_field }}
      </div>
      <div class="form-group col-md-4">
        {{ form.SL|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ form.rMultiple|as_crispy_field }}
      </div>
      <div class="form-group col-md-6">
        {{ form.option|as_crispy_field }}
      </div>
      {{ form.stamp }}
    </div>
    <button type="submit" id="fx" class="btn btn-primary">Add Entry</button>
  </form>
  {% endif %}
  <form class="w-100" id="stamp_form" method="post" action="{% url 'stamp' %}" name="stamp_form" novalidate>
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-12">
        {{ t_form.date|as_crispy_field }}
      </div>
      {{ t_form.option }}
      {{ t_form.owner }}
    </div>
    <button type="submit" class="btn btn-primary">Add TimeStamp for {{ option }}</button>
  </form>
</div>
  </div>
		</div>
	</div>

trading/journal/templates/includes/fx_table.html
{% load static %}
<section class="option-heading">
<h2>Forex Journal
</h2>
<a href="{% url 'dashboard' 'binary' %}" class="btn btn-dark float-right" type="">
  Move to Options journal
</a>
</section>
<table class="table table-responsive-md table-dark">
  <thead>
    <tr>
      <th scope="col">Pair</th>
      <th scope="col">Option</th>
      <th scope="col">Date Start</th>
      <th scope="col">Date End</th>
      <th scope="col">Reasons</th>
      <th scope="col">Lessons</th>
      <th scope="col">Price</th>
      <th scope="col">Stop Loss</th>
      <th scope="col">Take Profit</th>
      <th scope="col">Reward Multiple</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody id="table-body">
    {% for x in stamps %}
  	<tr data-stamp-id="{{ x.id }}">
  	<tr id="{{ x.id }}" data-stamp-id="{{ x.id }}">
  		<td colspan="11" class="text-center">
  		<h2>{{ x.date|date:"E d, Y" }}</h2>
  		<button id="modal" value="{{ x.id }}" class="btn btn-info">
		Create New Trade Entry <span><img class="ml-1" height="30" width="30" src="{% static 'img/add.svg' %}" alt=""></span></button>
		<form class="d-inline" id="delete_stamp_form" action="{% url 'stamp_delete' x.id %}" data-value="{{ x.id }}">
          {% csrf_token %}
          <button type="submit" id="stamp_delete" class="btn btn-danger">
          Delete TimeStamp <span><img class="ml-1" height="30" width="30" src="{% static 'img/delete.svg' %}" alt=""></span></button>
        </form>
    <p data-id="{{ x.id }}" class="m-0 mt-3">{% if x.forex.all %} {{ x.forex.all|length }} Entries {% else %} No Entries yet. {% endif %}</p>

	</td></tr>
  {% for entry in x.forex.all reversed%}
    <tr id="{{ entry.entry_id }}" data-stamp-id="{{ x.id }}">
      <td class="market">{{ entry.pair }}
      </td>
      <td class="span">{% if entry.option == "b" %}<span class="badge badge-success">{{ entry.get_option_display }}</span>{% else %}<span class="badge badge-danger">{{ entry.get_option_display }}</span>{% endif %}</td>
      <td class="span">August 23, 2019 19:18</td>
      <td class="span">August 23, 2019</td>
      <td>
        <p>{{ entry.reason.text }}</p>
        <button class="btn btn-info" href="#" id="image">
          View Image
        </button>
      </td>
      <td>
        <p>{{ entry.lesson.text }}</p>
        <button class="btn btn-info" href="#" id="image">
          View Image
        </button>
      </td>
      <td class="span">{{ entry.price }}</td>
      <td class="span">{{ entry.SL }}</td>
      <td class="span">{{ entry.TP }}</td>
      <td class="span">{{ entry.rMultiple }} R</td>
      <td>
        <form id="delete_form" action="{% url 'forex_d' entry.entry_id %}" data-stamp="{{ x.id }}" data-value="{{ entry.entry_id }}">
          {% csrf_token %}
          <button type="submit" id="entry_delete" class="btn btn-danger">
          X</button>
        </form>
      </td>
    </tr>
    {% empty %}
    {% endfor %}
</tr>
{% empty %}
<tr class="text-center"> No Timestamps </tr>
    {% endfor %}
  </tbody>
</table>