trading/trading/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from journal.views import index, dashboard,\
    forex_detail, binary_detail, forex, binary, stamp
from user.views import RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('option/<str:option>', dashboard, name='dashboard'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('forex/new', forex, name='forex'),
    path('binary/new', binary, name='binary'),
    path('stamp/new', stamp, name='stamp'),
    path('stamp/delete/<uuid:id>', stamp, name='stamp_delete'),
    path('forex/<uuid:id>', forex_detail, name='forex_d'),
    path('binary/<uuid:id>', binary_detail, name='binary_d'),
    path('login', LoginView.as_view(template_name='login.html'), name='login'),
    path('register', RegisterView.as_view(), name='register'),
]

trading/journal/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.


class TimeStamp(models.Model):
    CHOICE = (('forex', 'forex'), ('binary', 'binary'))

    date = models.DateField()
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    option = models.CharField(choices=CHOICE, max_length=10, blank=True)

    def __str__(self):
        return f"Timestamp for {self.date}"

    class Meta:
        ordering = ['-date']


class BaseManager(models.Manager):
    arguments = ('r_text', 'l_text', 'r_image', 'l_image')

    def create_entry(self, **kwargs):
        r_text, l_text, r_image, l_image = [
            kwargs.pop(val) for val in self.arguments]

        entry = self.model.objects.create(**kwargs)
        Reason.objects.create(image=r_image, text=r_text, entry=entry)
        Lesson.objects.create(image=l_image, text=l_text, entry=entry)
        return entry


class BaseEntry(models.Model):
    entry_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    CHOICE = (('b', 'Buy'), ('s', 'Sell'))
    pair = models.CharField(max_length=7, )
    option = models.CharField(choices=CHOICE, max_length=1, default='b')
    objects = BaseManager()

    def __str__(self):
        return f"Entry for {self.pair} @ {self.stamp.date}"


class ForexEntry(BaseEntry):
    timeStart = models.DateTimeField()
    timeEnded = models.DateTimeField()
    rMultiple = models.IntegerField()
    SL = models.FloatField()
    price = models.FloatField()
    TP = models.FloatField()
    stamp = models.ForeignKey(
        TimeStamp, on_delete=models.CASCADE,
        related_name='forex'
    )


class BinaryEntry(BaseEntry):

    CHOICE = (
        ('w', 'Win'),
        ('l', 'Lose'),
    )
    payout = models.IntegerField()
    result = models.CharField(choices=CHOICE, max_length=1)
    time = models.TimeField()
    stamp = models.ForeignKey(
        TimeStamp, on_delete=models.CASCADE,
        related_name='binary'
    )


class ContentBase(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(
        upload_to='user_directory_path', blank=True, null=True)
    text = models.TextField()

    class Meta:
        abstract = True


class Reason(ContentBase):
    entry = models.OneToOneField(
        'BaseEntry',
        on_delete=models.CASCADE,
        related_name='reason'
    )


class Lesson(ContentBase):
    entry = models.OneToOneField(
        'BaseEntry',
        on_delete=models.CASCADE,
        related_name='lesson'
    )

trading/journal/forms.py
from django import forms
from .models import TimeStamp, ForexEntry, BinaryEntry, Reason, Lesson


class ReasonForm(forms.Form):
    r_text = forms.CharField(label='Reasons', widget=forms.Textarea)
    r_image = forms.FileField(label='Reason Image')


class LessonForm(forms.Form):
    l_text = forms.CharField(label='Lessons', widget=forms.Textarea)
    l_image = forms.FileField(label='Lesson Image')


class StampForm(forms.ModelForm):
    option = forms.CharField(
        widget=forms.HiddenInput,
    )

    owner = forms.CharField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = TimeStamp
        fields = '__all__'


class ForexEntryForm(forms.ModelForm):
    SL = forms.FloatField(label='Stop Loss', required=True)
    TP = forms.FloatField(label='Take Profit', required=True)
    timeStart = forms.DateTimeField(label='Trade Start')
    timeEnded = forms.DateTimeField(label='Trade End')
    stamp = forms.UUIDField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = ForexEntry
        fields = '__all__'


class BinaryEntryForm(forms.ModelForm):
    stamp = forms.UUIDField(
        widget=forms.HiddenInput,
    )

    class Meta:
        model = BinaryEntry
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pair'].widget.attrs.update(
            {
                'placeholder': 'Currency Traded'})
        self.fields['payout'].widget.attrs.update(
            {
                'placeholder': 'Payout Rate'})

trading/journal/views.py
# Django Imports
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.template import Context, engines
from django.template.backends.utils import csrf_token_lazy
from django.utils.dateparse import parse_date

# Dependency Imports
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response

# Application Imports
from .forms import ForexEntryForm, BinaryEntryForm, StampForm,\
    ReasonForm, LessonForm
from .models import ForexEntry, BinaryEntry, TimeStamp
from .serializers import StampSerializer, BinarySerializer, ForexSerializer


LINK_FOREX = "journal/fx.html"
LINK_BINARY = "journal/binary.html"
LINK_STAMP = "journal/stamp.html"

engine = engines['django'].engine
fx_template = engine.get_template(LINK_FOREX)
binary_template = engine.get_template(LINK_BINARY)
stamp_template = engine.get_template(LINK_STAMP)


def login(request):
    return render(request, 'login.html')


@login_required
def index(request):
    form = ForexEntryForm()
    return render(request, 'index.html', context={'form': form})


@login_required
def dashboard(request, option):
    if option == 'forex':
        form = ForexEntryForm()
    elif option == 'binary':
        form = BinaryEntryForm()
    else:
        return Http404()
    timestamps = TimeStamp.objects.filter(
        option=option,
        owner=request.user
    )
    context = {
        'form': form, 'option': option,
        't_form': StampForm(
            initial={'option': option, 'owner': request.user.id}),
        "stamps": timestamps,
        'l_form': LessonForm(),
        'r_form': ReasonForm()
    }
    return render(request, 'dashboard.html', context=context)


@api_view(['POST', 'DELETE'])
def stamp(request, id=None):
    if request.method == "POST":
        stamp = StampSerializer(data=request.data)

        if stamp.is_valid():
            stamp.save()
            csrf_token = csrf_token_lazy(request)
            date = parse_date(stamp.data["date"]).strftime('%B %d, %Y')
            context = Context(
                {"stamp": stamp.data, "csrf_token": csrf_token, 'date': date})
            data = dict(
                stamp.data,
                template=stamp_template.render(context=context))
            return Response(data=data)
        return Response(stamp.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        try:
            TimeStamp.objects.get(id=id).delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except TimeStamp.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)


def post_wrapper(request, serializer_class, template):
    if request.method == "POST":
        serializer = serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            csrf_token = csrf_token_lazy(request)
            context = Context(
                {"entry": serializer.data, "csrf_token": csrf_token})
            data = dict(
                serializer.data,
                template=template.render(context=context))
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def forex(request):
    return post_wrapper(request, ForexSerializer, fx_template)


@api_view(['POST'])
def binary(request):
    return post_wrapper(request, BinarySerializer, binary_template)


def detail_wrapper(request, entry, serializer_class, id):
    try:
        entry = entry.objects.get(entry_id=id)
    except ForexEntry.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'DELETE':
        entry.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    elif request.method == 'PUT':
        serializer = serializer_class(entry, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(data=serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE', 'PUT'])
def forex_detail(request, id):
    return detail_wrapper(request, ForexEntry, ForexSerializer, id)


@api_view(['DELETE', 'PUT'])
def binary_detail(request, id):
    return detail_wrapper(request, BinaryEntry, BinarySerializer, id)

trading/journal/templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content= "width=device-width, initial-scale=1.0">
	<title>Dashboard</title>
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/dashboard.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Oswald|Slabo+27px&display=swap" rel="stylesheet">

</head>
<body>
	{% include 'includes/forms.html' %}
	<nav class="nav fixed-top m" id="nav">
		<h3>{% if option == 'binary' %}Binary Option{% else %}Forex{% endif %}</h3>
    {% comment %}<h6>{% if user.is_authenticated %}{{ user }}{% endif %}</h6>{% endcomment %}
		<button id="timestamp" class="btn btn-info" name="timestamp">
		Create New TimeStamp <span><img class="ml-1" height="30" width="30" src="{% static 'img/create.svg' %}" alt=""></span>
	</button>
  <a href="{% url 'logout' %}" class="btn btn-danger float-right" type="">
  Logout
</a>

	</nav>
  <div>
</div>
  {% if option == 'binary' %}
  {% include 'includes/binary_table.html' %}
  {% elif option == 'forex' %}
  {% include 'includes/fx_table.html' %}
  {% endif %}
  <footer class="footer">
    <nav class="footer-nav">
      <p>Developed and Designed by <strong>Ibaakee Ledum</strong> @ Froxine Tech</p>
      <p class="mt-1">All Rights Reserved <small>(c)</small> 2019</p>
    </nav>
  </footer>
	<script type="text/javascript" src="{% static 'js/axios.min.js' %}"></script>
  <script type="text/javascript">
    // SET ALL VARIABLES

    var modal = document.getElementById("myModal");
    var alertModal = document.getElementById("alertModal");
    var imageModal = document.getElementById("imageModal");
    var imageBtnTrigger = document.querySelectorAll("button#image");
    var imageCloseTrigger = document.getElementById("imageClose");
    var timeStampBtn = document.getElementById("timestamp");
    var newEntryEvent = document.querySelectorAll("button#modal");
    var span = document.getElementById("span");
    var newEntryForm = document.forms.namedItem("trading_form");
    var newStampForm = document.forms.namedItem("stamp_form");
    var dForm = document.querySelectorAll("form#delete_form");
    var stampForm = document.querySelectorAll("form#delete_stamp_form");
    var alertBox = document.getElementById("alertBox");
    var alertButtons = document.querySelectorAll("#alertBox button");


  </script>
  <script type="text/javascript">
    // Set Togglers and Form Display properties

    function btnEvent(e){
      newEntryForm.querySelectorAll("input#id_stamp")[0].value = e.target.value
      newStampForm.style = "display:none;";
      newEntryForm.style = "display:block;";
      modal.style = "display:flex;";
    }

    timeStampBtn.addEventListener('click', (e)=>{
      newEntryForm.style = "display:none;";
      newStampForm.style = "display:block;"
      modal.style = "display:flex;";
    })

    imageCloseTrigger.onclick = function(event){
      imageModal.style = "display:none;"
    }

    span.onclick = function(event){
      modal.style = "display:none;"
    }
  </script>
  <script type="text/javascript">
    // SET ALL HANDLER FUNCTIONS

    // SET ALL DELETE FUNCTIONS

    function setDeleteStamp(e) {
      e.preventDefault();
      let data = new FormData(e.target);
      axios({
        method: "delete",
        url: e.target.action,
        data: data,
        headers:{
          'X-CSRFToken': data.get("csrfmiddlewaretoken")
        }
      }).then((response)=>{
        var row = document.querySelectorAll(`tr[data-stamp-id='${e.target.dataset.value}']`);
        row.forEach((element)=>element.remove())
      }).catch((response)=>{
        console.log(response)
      })
      e.preventDefault();
    }


    function setDeleteHandler(e) {
      let data = new FormData(e.target);
      axios({
        method: "delete",
        url: e.target.action,
        data: data,
        headers:{
          'X-CSRFToken': data.get("csrfmiddlewaretoken")
        }
      }).then((response)=>{
        var row = document.getElementById(e.target.dataset.value);
        var text = document.querySelector(`p[data-id='${e.target.dataset.stamp}']`);
        var no = parseInt(text.innerText.split(" ")[0]);
        var val = no - 1
        if (val === 0){
          text.innerText = "No Entries yet."
        }
        else{
          text.innerText = `${val} Entries`
        }
        row.remove()
      }).catch((response)=>{
        console.log(response)
      })
      e.preventDefault();
    }

    function setAlertButtonEvent(func, event){
      alertModal.style = "display:flex;";
      alertButtons.forEach((element)=>{
        element.onclick = function(e){
          var option = e.target.dataset.option
          if (option === "no"){
            alertModal.style = "display:none;";
          }
          else if(option === "yes"){
            alertModal.style = "display:none;";
            func(event)
          }
        }
      })
    }

    function deleteWrapper(func, elementTag){
      elementTag.forEach((element)=>{
        element.addEventListener('submit', (e)=>{
          setAlertButtonEvent(func, e);
          e.preventDefault();
          })
      })
    }

    function setHandlerWrapper(func, element, event) {
      element.forEach((el)=>{
        el.addEventListener(event,(e)=>{
          func(e)
        })
      })
    }

    function setDeleteEntryHandler() {
      deleteWrapper(setDeleteHandler, dForm);
    }

    function setDeleteStampHandler(){
      deleteWrapper(setDeleteStamp, stampForm);
    }

    function imageEvent(event){
      imageModal.style = "display:flex;"
    }

    function setImageHandler(button){
      setHandlerWrapper(imageEvent, button, 'click');
    }

    function setNewEntryHandler(button) {
      setHandlerWrapper(btnEvent, button, 'click');
    }

    setNewEntryHandler(newEntryEvent);
    setDeleteEntryHandler()
    setDeleteStampHandler()
    setImageHandler(imageBtnTrigger)
  </script>
  <script type="text/javascript">
    // SET FORM SUBMIT EVENTS FOR TIMESTAMPs AND ENTRY( Binary / Forex )

    newStampForm.onsubmit = function(e){
      let data = new FormData(e.target);
      newStampForm.reset()
      axios({
        method: 'post',
        url: this.action,
        data: data
      }).then((response)=>{
        console.log(response.data)
        modal.style = "display:none;"
        setTimeout(()=>{
          var table_body  = document.getElementById("table-body");
          table_body.insertAdjacentHTML("afterBegin",response.data["template"]);
          var stamp = document.querySelector(`tr[id='${response.data.id}']`);
          stamp.querySelector("#modal").addEventListener('click', (e)=>btnEvent(e));
          stamp.querySelector("form").addEventListener('submit', (e)=>{
            e.preventDefault();
            setAlertButtonEvent(setDeleteStamp, e)
          });
        }, 500)

      }).catch(({response})=>{
        console.log(response.data)
      })
      e.preventDefault();
    }

    function onEntrySuccess(argument) {
      // body...
    }

    newEntryForm.onsubmit = function(e){
      let data = new FormData(e.target);
      newEntryForm.reset()
      axios({
        method: 'post',
        url: this.action,
        data: data
      }).then((response)=>{
        var stamp_element  = document.getElementById(response.data["stamp"]);
        modal.style = "display:none;"
        setTimeout(()=>{
          stamp_element.insertAdjacentHTML("afterEnd",response.data["template"]);
          var row = document.getElementById(response.data["entry_id"])
          var text = document.querySelector(`p[data-id='${response.data["stamp"]}']`)
          var no = parseInt(text.innerText.split(" ")[0])
          if (isNaN(no)){
            text.innerText = "1 Entries"
          }
          else{
            text.innerText = `${no + 1} Entries`
          }
          row.querySelector("form#delete_form").addEventListener(
            'submit',(e)=>{
              e.preventDefault();
              setAlertButtonEvent(setDeleteHandler, e)
            })
        }, 500);
      }).catch(({response})=>{
        console.log(response.data)
      })
      e.preventDefault();
    }
  </script>

</body>
</html>

trading/journal/templates/index.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Oswald|Slabo+27px&display=swap" rel="stylesheet">

</head>
<body>
	<div class="app">
		<div class="app-second"></div>
		<div class="wrapper">
			<h1 class="zoomIn h">Welcome back "{{ request.user }}"</h1>
			<p>Which Trading journal do you want to move to ?</p>
			<div class="buttons">
				<a href="{% url 'dashboard' option='forex' %}" class="btn mx-3 forex btn-danger">
					Forex Journal
				</a>
				<a href="{% url 'dashboard' option='binary' %}" class="btn mx-3 binary btn-success">
					Binary Options
				</a>
			</div>
		</div>
	</div>

</body>
</html>